chore: use self-hosted runner for pypi publish work; version 0.2.1

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
 
     steps:
     - uses: actions/checkout@v2
@@ -18,16 +18,24 @@ jobs:
       with:
         python-version: 3.10.14
 
-    - name: Install Poetry
-      run: |
-        curl -sSL https://install.python-poetry.org | python3 -
+    - name: Set up Poetry
+        run: |
+          poetry --version
+          if [ $? -ne 0 ]; then
+            echo "Poetry not found, setting up..."
+            python3 -m pip install --upgrade pip
+            python3 -m pip install pipx --user
+            python3 -m pipx ensurepath
+            pipx install poetry
+          fi
+          poetry install --extras docs
 
     - name: Build with poetry
-      run: poetry build
+      run: make build
 
   pypi-publish:
     name: upload release to PyPI
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     # Specifying a GitHub environment is optional, but strongly encouraged
     environment: release
     permissions:
